scripts/snapshot. Streamlined code with helper functions.

diff --git a/scripts/snapshot b/scripts/snapshot
--- a/scripts/snapshot
+++ b/scripts/snapshot
@@ -3,6 +3,7 @@
 # Snapshot
 # BASH script for creating standard and archive snapshots using the Google Cloud SDK
 # By Nicholas Grogg
+# Revision: 20260727
 
 # Color variables
 ## Errors
@@ -38,6 +39,83 @@ function helpFunction(){
     " "
 }
 
+# Helper Function to fetch instance zone and disk name
+getServerInfo() {
+    printf "%s\n" \
+    "Getting server zone and disk name" \
+    "----------------------------------------------------"
+
+    ## Local variables for passed values
+    local server="$1"
+    local project="$2"
+
+    ## Find server zone and disk
+    serverZone=$(gcloud compute instances list --project="$project" \
+        --filter="name=$server" \
+        --format="value(zone.basename())" | head -n 1)
+
+    diskName=$(gcloud compute disks list --project="$project" \
+        --filter="name~$server" \
+        --format="value(name)" | head -n 1)
+
+    ## If values are null exit with error
+    if [[ -z "$serverZone" || -z "$diskName" ]]; then
+        printf "%s\n" \
+        "${red}ISSUE DETECTED - Could not find server or disk!" \
+        "----------------------------------------------------" \
+        "Double check values and re-run script.${normal}"
+        exit 1
+    fi
+}
+
+# Helper function to validate snapshots
+validateSnapshot() {
+    printf "%s\n" \
+    "Snapshot Validation" \
+    "----------------------------------------------------"
+
+    ## Local variables for passed values
+    local snapshotName="$1"
+    local project="$2"
+    local snapshotSize
+
+    ## Find snapshot size
+    snapshot_size=$(gcloud compute snapshots describe "$snapshotName" \
+        --project="$project" \
+        --format="value(storageBytes)" 2>/dev/null)
+
+    ## If gcloud command failed
+    if [[ $? -ne 0 || -z "$snapshot_size" ]]; then
+        printf "%s\n" \
+        "${red}ISSUE DETECTED - Gcloud command failed!"
+        "----------------------------------------------------" \
+        "Double check if snapshot exists" \
+        " " \
+        "Take snapshot manually if need be.${normal}" \
+        " "
+
+        exit 1
+    fi
+
+    ## If snapshot size is empty return error
+    if [[ "$snapshot_size" -eq 0 ]]; then
+        printf "%s\n" \
+        "${red}ISSUE DETECTED - Snapshot size is 0 B!"
+        "----------------------------------------------------" \
+        "Do not proceed!${normal}" \
+        " "
+
+        exit 1
+    else
+        printf "%s\n" \
+        "${green}Snapshot size > 0 B " \
+        "----------------------------------------------------" \
+        "Proceed with work effort.${normal}"
+
+        exit 0
+    fi
+}
+
 # Function to create a standard snapshot
 function createStandard(){
     printf "%s\n" \
@@ -45,13 +123,13 @@ function createStandard(){
     "----------------------------------------------------"
 
     ## Store passed values
-    server=$1
-    purpose=$2
-    initials=$3
-    project=$4
+    local server="$1"
+    local purpose="$2"
+    local initials="$3"
+    local project="$4"
 
     ## Variable validation
-    if [[ -z $server ]] || [[ -z $purpose ]] || [[ -z $initials ]] || [[ -z $project ]]; then
+    if [[ -z "$server" ]] || [[ -z "$purpose" ]] || [[ -z "$initials" ]] || [[ -z "$project" ]]; then
         printf "%s\n" \
         "${red}ISSUE DETECTED - Variable missing " \
         "----------------------------------------------------" \
@@ -61,42 +139,42 @@ function createStandard(){
         exit 1
     fi
 
+    ## Retrieve zone & disk before asking for confirmation
+    getServerInfo "$server" "$project"
+
     ## Confirmation
     printf "%s\n" \
     "${yellow}IMPORTANT: Value Confirmation" \
     "----------------------------------------------------" \
-    "Snapshot Type:" \
-    "Standard" \
-    "" \
-    "Server: " "$server" \
-    "" \
-    "Purpose: " "$purpose" \
-    "" \
-    "Sysadmin: "  "$initials" \
-    "" \
-    "Project: "  "$project" \
-    "" \
+    "Snapshot Type: Standard" \
+    "Server:        $server" \
+    "Purpose:       $purpose" \
+    "Sysadmin:      $initials" \
+    "Project:       $project" \
+    " " \
     "If all clear, press enter to proceed or ctrl-c to cancel${normal}"
 
     read junkInput
 
     ## Create snapshot
-    ### Find server zone
-    serverZone=$(gcloud compute instances list --project $project | grep $server | awk '{print $2}'| head -n 1)
+    ### Set snapshot name
+    local snapshotName="${initials}-${diskName}-${purpose}-$(date +"%Y%m%d")"
 
-    ### Find server disk
-    diskName=$(gcloud compute disks list --project $project | grep $server | awk '{print $1}' | head -n 1)
-
-    #TODO: Flag storage-location variable may need adjusted depending on needs
-    ### Take snapsho
-    gcloud compute disks snapshot $diskName --snapshot-names=$initials-$diskName-$purpose-$(date +"%Y%m%d") --storage-location=us --zone $serverZone --project $project
+    ### Take snapshot
+    gcloud compute disks snapshot "$diskName" \
+        --snapshot-names="$snapshotName" \
+        --storage-location="us" \
+        --zone="$serverZone" \
+        --project="$project"
 
     ### Was snapshot taken successfully?
     if [[ $? = 0 ]]; then
         printf "%s\n" \
-        "${green}Snapshot taken " \
+        "${green}Snapshot taken" \
         "----------------------------------------------------" \
         "Proceeding to validation ${normal}"
+
+        validateSnapshot "$snapshotName" "$project"
     else
         printf "%s\n" \
         "${red}ISSUE DETECTED - Something went wrong!" \
@@ -104,46 +182,6 @@ function createStandard(){
         "Exiting! ${normal}"
         exit 1
     fi
-
-    ## Snapshot validation
-    printf "%s\n" \
-    "Snapshot Validation" \
-    "----------------------------------------------------" \
-
-    ### Get snapshot name
-    snapshotName="$initials-$diskName-$purpose-$(date +"%Y%m%d")"
-
-    ### Get size of snapshot
-    snapshotSize=$(gcloud compute snapshots describe $snapshotName --project $project | grep storageBytes: | awk '{print $2}')
-
-    ### Did command execute successfully?
-    if [[ $? != 0 ]]; then
-        printf "%s\n" \
-        "${red}ISSUE DETECTED - Gcloud command failed!" \
-        "----------------------------------------------------" \
-        "Exiting! ${normal}"
-        exit 1
-    fi
-
-    ### Is snapshot empty at 0 B?
-    if [[ "$snapshotSize" == "'0'" ]]; then
-        printf "%s\n" \
-        "${red}ISSUE DETECTED - Snapshot size is 0 B!" \
-        "----------------------------------------------------" \
-        "Do not proceed with current work effort! " \
-        " " \
-        "Review disk and take snapshot manually" \
-        " " \
-        "Exiting! ${normal}"
-        exit 1
-    else
-        printf "%s\n" \
-        "${green}Snapshot size > 0 B" \
-        "----------------------------------------------------" \
-        "Proceed with work effort${normal}"
-        exit 0
-    fi
-
 }
 
 # Function to create an archive snapshot
@@ -153,12 +191,13 @@ function createArchive(){
     "----------------------------------------------------"
 
     ## Store passed values
-    server=$1
-    purpose=$2
-    project=$3
+    local server="$1"
+    local purpose="$2"
+    local project="$3"
+    local shortname="$4"
 
     ## Variable validation
-    if [[ -z $server ]] || [[ -z $purpose ]] || [[ -z $project ]]; then
+    if [[ -z "$server" ]] || [[ -z "$purpose" ]] || [[ -z "$project" ]] || [[ -z "$shortname" ]]; then
         printf "%s\n" \
         "${red}ISSUE DETECTED - Variable missing " \
         "----------------------------------------------------" \
@@ -168,34 +207,55 @@ function createArchive(){
         exit 1
     fi
 
+    ## Retrieve zone & disk info
+    getServerInfo "$server" "$project"
+
     ## Confirmation
     printf "%s\n" \
     "${yellow}IMPORTANT: Value Confirmation" \
     "----------------------------------------------------" \
-    "Snapshot Type:" \
-    "Archive" \
+    "Snapshot Type: Archive" \
+    "Server:        $server" \
+    "Purpose:       $purpose" \
+    "Project:       $project" \
+    "Shortname:     $shortname" \
     "" \
-    "Server: " "$server" \
-    "" \
-    "Purpose: " "$purpose" \
-    "" \
-    "Project: "  "$project" \
-    "" \
-    "Server should be powered off for best results!" \
+    "Server needs to be powered off!" \
     "" \
     "If all clear, press enter to proceed or ctrl-c to cancel${normal}"
     read junkInput
 
-    ## Create snapshot
-    ### Find server zone
-    serverZone=$(gcloud compute instances list --project $project | grep $server | awk '{print $2}'| head -n 1)
+    ## Is the server powered off?
+    status=$(gcloud compute instances describe "$server" --project="$project" --zone="$serverZone" --format="value(status)" 2>/dev/null)
 
-    ### Find server disk
-    diskName=$(gcloud compute disks list --project $project | grep $server | awk '{print $1}' | head -n 1)
+    if [[ "$status" != "TERMINATED" ]]; then
+        printf "%s\n" \
+        "${red}ISSUE DETECTED - Server is not powered off!" \
+        "----------------------------------------------------" \
+        "Archive snapshots require the server powered off." \
+        "Shut down the server and re-run the script." \
+        " " \
+        "Exiting!${normal}"
 
-    #TODO: Flag storage-location variable may need adjusted depending on needs
+        exit 1
+    else
+        printf "%s\n" \
+        "${green}Server powered off" \
+        "----------------------------------------------------" \
+        "Proceeding${normal}"
+    fi
+
+    ### Variable name for snapshot
+    local snapshotName="${shortname}-${diskName}-${purpose}-$(date +"%Y%m%d")"
+
     ### Take snapshot
-    gcloud compute snapshots create $diskName-$purpose-$(date +"%Y%m%d") --source-disk $diskName --storage-location=us --source-disk-zone $serverZone --project $project --snapshot-type ARCHIVE
+    gcloud compute snapshots create "$snapshotName" \
+        --source-disk="$diskName" \
+        --storage-location="us" \
+        --source-disk-zone="$serverZone" \
+        --project="$project" \
+        --snapshot-type="ARCHIVE" \
+        --labels="auth-to-delete=no,customer=$shortname"
 
     ### Was snapshot taken successfully?
     if [[ $? = 0 ]]; then
@@ -203,6 +263,9 @@ function createArchive(){
         "${green}Snapshot taken " \
         "----------------------------------------------------" \
         "Moving to validation ${normal}"
+
+        validateSnapshot "$snapshotName" "$project"
+
     else
         printf "%s\n" \
         "${red}ISSUE DETECTED - Something went wrong!" \
@@ -210,43 +273,6 @@ function createArchive(){
         "Exiting! ${normal}"
         exit 1
     fi
-
-    ## Snapshot validation
-    printf "%s\n" \
-    "Snapshot Validation" \
-    "----------------------------------------------------" \
-
-    ### Get snapshot name
-    snapshotName="$diskName-$purpose-$(date +"%Y%m%d")"
-
-    ### Get size of snapshot
-    snapshotSize=$(gcloud compute snapshots describe $snapshotName --project $project | grep storageBytes: | awk '{print $2}')
-
-    ### Did command execute successfully?
-    if [[ $? != 0 ]]; then
-        printf "%s\n" \
-        "${red}ISSUE DETECTED - Gcloud command failed!" \
-        "----------------------------------------------------" \
-        "Exiting! ${normal}"
-        exit 1
-    fi
-
-    ### Is snapshot empty at 0 B?
-    if [[ "$snapshotSize" == "'0'" ]]; then
-        printf "%s\n" \
-        "${red}ISSUE DETECTED - Snapshot size is 0 B!" \
-        "----------------------------------------------------" \
-        "Do not proceed with current work effort! " \
-        "Exiting! ${normal}"
-        exit 1
-    else
-        printf "%s\n" \
-        "${green}Snapshot size > 0 B" \
-        "----------------------------------------------------" \
-        "Proceed with work effort${normal}"
-        exit 0
-    fi
-
 }
 
 # Main, read passed flags
@@ -275,7 +301,7 @@ case "$1" in
     printf "%s\n" \
     "Archive snapshot flag passed" \
     "----------------------------------------------------"
-    createArchive $2 $3 $4
+    createArchive $2 $3 $4 $5
     ;;
 *)
     printf "%s\n" \
